### ISSUE TITLE
Should `category` be case insensitive?

### ISSUE THREAD

**Issue by bekapod** [holography/holograph#42]
Probably more of an issue when multiple people are working on the style guide, if one person references `atoms` and another `Atoms`, 2 links will appear in the navigation (expected?) but both link to the same page `atoms.html` - maybe parsing the category could be case insensitive.

Or maybe this can be a known "issue", just thought I'd raise in case you wanted to fix!

**Comment by chicgeek** [comment]
May be resolved with #36. Requires checking.
